name: Sshwifty-CI

on:
  push:
    branches: [master, dev]
    tags: ["**-release"]
  pull_request:

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - name: Checking out source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 20
      - name: Setting up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
      - name: Run CI
        run: |
          export GITHUB_USER="${{ github.repository_owner }}"
          export GITHUB_USER_TOKEN="${{ secrets.GITHUB_TOKEN }}"
          export DOCKER_HUB_USER="${{ secrets.DOCKER_HUB_USERNAME }}"
          export DOCKER_HUB_PASSWORD="${{ secrets.DOCKER_HUB_PASSWORD }}"
          export COVERALLS_TOKEN="${{ secrets.COVERALLS_TOKEN }}"

          export DOCKER_CUSTOM_COMMAND='echo "GitHub Action Build"'

          sudo apt-get update -y
          sudo apt-get upgrade -y
          sudo apt-get install libvips libvips-dev -y

          cp ./.ci.sh ./.github-action-ci-script.sh && chmod +x ./.github-action-ci-script.sh && time ./.github-action-ci-script.sh && rm ./.github-action-ci-script.sh
